version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Desktop/TurtlePlayground-service
    overwrite: yes
permissions:
  - object: /home/ubuntu/Desktop/TurtlePlayground-service
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: ubuntu